name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 9 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ secrets.NAME }}
          SETTING_JSON: ./.github/workflows/setting.json
      - name: Commit & Push
        run: |
          git config --global user.name ${{ secrets.NAME }}
          git config --global user.email ${{ secrets.NAME }}@naver.com
          git add -A .
          git commit -m "generated"
          git push
