name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ secrets.NAME }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push

  calendar:
    name: Full-year calendar
    uses: lowlighter/metrics@latest
    with:
      filename: metrics.plugin.isocalendar.fullyear.svg
      token: ${{ secrets.TOKEN }}
      base: ""
      plugin_isocalendar: yes
      plugin_isocalendar_duration: full-year
